---
meta:
  default:
    rabbitmq_tags:
      - blacksmith
      - dedicated
      - rabbitmq

    rabbitmq_plans:
      standalone:
        name: standalone
        description: A dedicated RabbitMQ server, with no redundancy or replication
        limit: 7
        type: standalone
        vm_type: default

releases:
- name:    rabbitmq-forge
  version: 0.5.13
  url:     https://github.com/blacksmith-community/rabbitmq-forge-boshrelease/releases/download/v0.5.13/rabbitmq-forge-0.5.13.tgz
  sha1:    74866b6ec5a2c577ead599e0ed34bb94b8b6a754

params:
  releases:
    - (( append ))
    - (( grab releases.rabbitmq-forge ))

instance_groups:
  - name: blacksmith
    jobs:
      - release: rabbitmq-forge
        name:    rabbitmq-blacksmith-plans
        properties:
          plans: (( grab params.rabbitmq_plans || meta.default.rabbitmq_plans ))
          service:
            id:          (( grab params.rabbitmq_service_id          || "rabbitmq" ))
            name:        (( grab params.rabbitmq_service_name        || params.rabbitmq_service_id || "rabbitmq" ))
            description: (( grab params.rabbitmq_service_description || "A dedicated RabbitMQ instance, deployed on-demand" ))
            tags:        (( grab params.rabbitmq_service_tags        || meta.default.rabbitmq_tags ))
            limit:       (( grab params.rabbitmq_service_limit       || 0 ))

