---
meta:
  default:
    redis_tags:
      - blacksmith
      - dedicated
      - redis

    redis_plans:
      standalone:
        name: standalone
        description: A dedicated Redis server, with no redundancy or replication
        limit: 7
        type: standalone
        vm_type: default
      standalone-6:
        name: standalone-6
        description: A dedicated Redis 6 server, with no redundancy or replication
        limit: 7
        type: standalone-6
        vm_type: default
releases:
- name:    redis-forge
  version: 0.6.1
  url:     https://github.com/blacksmith-community/redis-forge-boshrelease/releases/download/v0.6.1/redis-forge-0.6.1.tgz
  sha1:    f2d3ea11bea26771b571ecf02823b8dc7d55c1e9

params:
  releases:
    - (( append ))
    - (( grab releases.redis-forge ))

instance_groups:
  - name: blacksmith
    jobs:
      - release: redis-forge
        name:    redis-blacksmith-plans
        properties:
          plans: (( grab params.redis_plans || meta.default.redis_plans ))
          service:
            id:          (( grab params.redis_service_id          || "redis" ))
            name:        (( grab params.redis_service_name        || params.redis_service_id || "redis" ))
            description: (( grab params.redis_service_description || "A dedicated Redis instance, deployed on-demand" ))
            tags:        (( grab params.redis_service_tags        || meta.default.redis_tags ))
            limit:       (( grab params.redis_service_limit       || 0 ))
