---
params:
  ip:           (( param "Please specify the static IP address for the Blacksmith Service Broker" ))
  cloud_config: (( param "Please specify a complete BOSH v2 cloud-config, for the Blacksmith internal BOSH director to use" ))

  releases: []
  stemcells: []

meta:
  default:
    azs: [z1]
    host: (( grab params.fqdn || params.ip ))
    scheme: http
    blacksmith_port: 3000

exodus:
  broker_url: (( concat meta.scheme "://" meta.host ":" params.blacksmith_port ))
  broker_username: (( grab instance_groups.blacksmith.jobs.blacksmith.properties.broker.username ))
  broker_password: (( grab instance_groups.blacksmith.jobs.blacksmith.properties.broker.password ))
  bosh_username: (( grab instance_groups.blacksmith.jobs.blacksmith.properties.bosh.username ))
  bosh_password: (( grab instance_groups.blacksmith.jobs.blacksmith.properties.bosh.password ))
  bosh_address: (( grab instance_groups.blacksmith.jobs.blacksmith.properties.bosh.address ))
  bosh_cacert: (( vault meta.vault "/tls/ca:certificate" ))

instance_groups:
  - name:      blacksmith
    instances: 1
    stemcell:  default
    azs:             (( grab params.availability_zones || meta.default.azs ))
    vm_type:         (( grab params.vm_type   || "blacksmith" ))
    persistent_disk: (( grab params.disk_size || 20480 ))
    networks:
      - name:       (( grab params.network || "blacksmith" ))
        static_ips: [(( grab params.ip ))]
    jobs:
      - release: blacksmith
        name:    blacksmith
        properties:
          debug: (( grab params.blacksmith_debug || false ))
          env:   (( grab params.blacksmith_env   || params.env || "blacksmith" ))
          shareable:  (( grab params.shareable || false ))

          broker:
            port:     (( grab params.blacksmith_port || 3000 ))
            username: blacksmith
            password: (( vault meta.vault "/broker:password" ))

          bosh:
            username: blacksmith
            password: (( vault meta.vault "/users/blacksmith:password" ))
            address:  (( concat "https://" params.ip ":25555" ))
            stemcells:    (( grab params.stemcells ))
            releases:     (( grab params.releases ))
            cloud-config: (( grab params.cloud_config ))

releases:
- name:    blacksmith
  version: 1.5.2
  url:     https://github.com/blacksmith-community/blacksmith-boshrelease/releases/download/v1.5.2/blacksmith-1.5.2.tgz
  sha1:    34b33acf4de8b70f38860658bdaa9b04ffd59108

stemcells:
  - alias: default
    os:      (( grab params.stemcell_os      || "ubuntu-bionic"))
    version: (( grab params.stemcell_version || "latest" ))

update:
  serial: false
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  max_in_flight: 1
  max_errors: 1

