---
meta:
  shield:
    exodus: (( concat $GENESIS_EXODUS_MOUNT params.shield.deployment_env "/" params.shield.deployment_type ":" ))

    admin_username:  (( vault meta.shield.exodus "admin_username" ))
    admin_password:  (( vault meta.shield.exodus "admin_password" ))

    address:  (( vault meta.shield.exodus "url" ))
    agent:    (( vault meta.vault "/shield:agent" )) # TODO: this value is not set by the SHIELD kit.

params:
  shield:
    username: blacksmith
    password: (( vault meta.vault "/shield:password" ))
    tenant:   blacksmith
    store:    (( vault meta.vault "/shield:store" ))

instance_groups:
  - name: blacksmith
    jobs:
      - name:    blacksmith
        release: blacksmith
        properties:
          shield:
            enabled: true
            address: (( grab params.shield.address || meta.shield.address ))
            agent: (( grab params.shield.agent || meta.shield.agent ))
            auth_method: local # Only local authentication method is supported for this kit feature.
            username: (( grab params.shield.username ))
            password: (( grab params.shield.password ))
            tenant: (( grab params.shield.tenant ))
            store:  (( grab params.shield.store ))
            schedule: (( grab params.shield.schedule || "" ))
            retain: (( grab params.shield.retain || "" ))
