---
meta:
  default:
    azs:
      - (( replace ))
      - (( concat params.aws_region "a" ))

params:
  aws_key_name:    (( concat "vcap@" params.env ))
  aws_region:      (( param "What AWS region are you going to use?" ))
  aws_default_sgs: (( param "What security groups should VMs be placed in, if none are specified via Cloud Config?" ))

  stemcells:
    - name:    bosh-aws-xen-hvm-ubuntu-xenial-go_agent
      version: '621.125'
      url:     https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=621.125
      sha1:    a21e4f88d84f8fc8d7b3318cca712de2b6fd0b61

releases:
  - name:    bosh-aws-cpi
    version: 87
    url:     https://bosh.io/d/github.com/cloudfoundry/bosh-aws-cpi-release?v=87
    sha1:    a920cd1bdead3d6167273e763912becca2225ba6

instance_groups:
- name: blacksmith
  jobs:
  - name: aws_cpi
    release: bosh-aws-cpi
  properties:
    aws:
      access_key_id:           (( vault meta.vault "/aws:access_key" ))
      secret_access_key:       (( vault meta.vault "/aws:secret_key" ))
      default_key_name:        (( grab params.aws_key_name ))
      default_security_groups: (( grab params.aws_default_sgs ))
      region:                  (( grab params.aws_region ))
    director:
      cpi_job: aws_cpi
