---
meta:
  default:
    azs:
      - (( replace ))
      - (( concat params.aws_region "a" ))

params:
  aws_key_name:    (( concat "vcap@" params.env ))
  aws_region:      (( param "What AWS region are you going to use?" ))
  aws_default_sgs: (( param "What security groups should VMs be placed in, if none are specified via Cloud Config?" ))

  stemcells:
    - name:    bosh-aws-xen-hvm-ubuntu-jammy-go_agent
      version: '1.181'
      url:     https://storage.googleapis.com/bosh-aws-light-stemcells/1.181/light-bosh-stemcell-1.181-aws-xen-hvm-ubuntu-jammy-go_agent.tgz
      sha1:    2e113e50c47df57bfe9fe31a0d2bee3fab20af37

releases:
  - name:    bosh-aws-cpi
    version: 99
    url:     https://bosh.io/d/github.com/cloudfoundry/bosh-aws-cpi-release?v=99
    sha1:    ffc4a06d6728d88eb108418f886f46428c2a1bf2

instance_groups:
- name: blacksmith
  jobs:
  - name: aws_cpi
    release: bosh-aws-cpi
  properties:
    aws:
      access_key_id:           (( vault meta.vault "/aws:access_key" ))
      secret_access_key:       (( vault meta.vault "/aws:secret_key" ))
      default_key_name:        (( grab params.aws_key_name ))
      default_security_groups: (( grab params.aws_default_sgs ))
      region:                  (( grab params.aws_region ))
    director:
      cpi_job: aws_cpi
