---
params:
  azure_environment:    AzureCloud
  azure_resource_group: (( param "Specify the resource group for Azure" ))
  azure_default_sg:     (( param "Specify the default security group for your Azure VMs" ))

  stemcells:
    - name:    bosh-azure-hyperv-ubuntu-bionic-go_agent
      version: '1.36'
      url:     https://storage.googleapis.com/bosh-core-stemcells/1.36/bosh-stemcell-1.36-azure-hyperv-ubuntu-bionic-go_agent.tgz
      sha1:    6d51e4628cd6557f2a6d64350ce7d697b7a34e47

releases:
  - name:    bosh-azure-cpi
    version: "37.5.0"
    sha1:    ce148b7172772be636703773f57d4f17e7676cd1
    url:     https://bosh.io/d/github.com/cloudfoundry/bosh-azure-cpi-release?v=37.5.0

instance_groups:
- name: blacksmith
  jobs:
  - name: azure_cpi
    release: bosh-azure-cpi
  properties:
    director:
      cpi_job: azure_cpi

    azure:
      environment: (( grab params.azure_environment ))
      subscription_id: (( vault meta.vault "/azure:subscription_id" ))
      tenant_id: (( vault meta.vault "/azure:tenant_id" ))
      client_id: (( vault meta.vault "/azure:client_id" ))
      client_secret: (( vault meta.vault "/azure:client_secret" ))
      resource_group_name: (( grab params.azure_resource_group ))
      default_security_group: (( grab params.azure_default_sg ))
      ssh_user: vcap
      ssh_public_key: (( vault meta.vault "/azure/ssh:public" ))
      use_managed_disks: true
