---
params:
  google_project: (( param "Enter the project name that your BOSH will be deployed into" ))

  ntp: # use GCP ntp
    - (( replace ))
    - time.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com

  stemcells:
    - name:    bosh-google-kvm-ubuntu-bionic-go_agent
      version: '1.36'
      url:     https://storage.googleapis.com/bosh-gce-light-stemcells/1.36/light-bosh-stemcell-1.36-google-kvm-ubuntu-bionic-go_agent.tgz
      sha1:    962c958e17012bd8bd003568f7978c465d83d12b

releases:
  - name:    bosh-google-cpi
    version: 40.0.4
    url:     https://bosh.io/d/github.com/cloudfoundry/bosh-google-cpi-release?v=40.0.4
    sha1:    723cbba1e027bf9b628fe413ba16d90415057edc

instance_groups:
  - name: blacksmith
    jobs:
      - name: google_cpi
        release: bosh-google-cpi
        properties:
          google:
          project: (( grab params.google_project ))
          json_key: (( vault meta.vault "/google:json_key" ))
        director:
          cpi_job: google_cpi
