---
meta:
  vsphere:
    ephemeral:  (( join "|" params.vsphere_ephemeral_datastores ))
    persistent: (( join "|" params.vsphere_persistent_datastores ))

params:
  vsphere_ephemeral_datastores:  (( param "Please specify your vSphere ephemeral datastore pattern" ))
  vsphere_persistent_datastores: (( param "Please specify your vSphere persistent datastore pattern" ))
  vsphere_clusters:              (( param "Please specify your vSphere clusters" ))
  vsphere_datacenter:            (( param "Please specify your vSphere Datacenter Name" ))

  stemcells:
    - name:    bosh-vsphere-esxi-ubuntu-bionic-go_agent
      version: '1.36'
      url:     https://storage.googleapis.com/bosh-core-stemcells/1.36/bosh-stemcell-1.36-vsphere-esxi-ubuntu-bionic-go_agent.tgz
      sha1:    4cf0de2078b94dfdeb01ac6e3af7a32c31df5171

releases:
  - name:    bosh-vsphere-cpi
    version: '59'
    url:     https://bosh.io/d/github.com/cloudfoundry/bosh-vsphere-cpi-release?v=59
    sha1: "132a1548f244866e09c6ef770b248ad703b844ba"

instance_groups:
  - name: blacksmith
    jobs:
      - { release: bosh-vsphere-cpi, name: vsphere_cpi }

    properties:
      director:
        cpi_job: vsphere_cpi

      vcenter:
        address:  (( vault meta.vault "/vsphere:address"  ))
        user:     (( vault meta.vault "/vsphere:user"     ))
        password: (( vault meta.vault "/vsphere:password" ))

        datacenters:
          - name:     (( grab params.vsphere_datacenter ))
            clusters: (( grab params.vsphere_clusters   ))

            vm_folder:       (( concat params.env "-blacksmith/vms"       ))
            template_folder: (( concat params.env "-blacksmith/templates" ))
            disk_path:       (( concat params.env "-blacksmith/disks"     ))

            datastore_pattern:            (( concat "^(" meta.vsphere.ephemeral  ")$" ))
            persistent_datastore_pattern: (( concat "^(" meta.vsphere.persistent ")$" ))
